language: node_js

matrix:
  include:
    - stage: test
      name: 'Test UI lint'
      env:
        - CI_INSTALL_UI=true
        - CI_TEST_UI_LINT=true
      script: ./packages/scripts/src/bash/ci-test.sh

    - stage: test
      name: 'Test UI unit'
      env:
        - CI_INSTALL_UI=true
        - CI_TEST_UI_UNIT=true
      script: ./packages/scripts/src/bash/ci-test.sh

    - stage: test
      name: 'Test models, common, scripts and docs'
      env:
        - CI_INSTALL_COMMON=true
        - CI_INSTALL_DOCS=true
        - CI_INSTALL_MODELS=true
        - CI_INSTALL_SCRIPTS=true
        - CI_INSTALL_SCRIPTS=true
        - CI_TEST_COMMON_LINT=true
        - CI_TEST_COMMON_UNIT=true
        - CI_TEST_DOCS_LINT=true
        - CI_TEST_DOCS_UNIT=true
        - CI_TEST_MODELS_LINT=true
        - CI_TEST_MODELS_LINT=true
        - CI_TEST_SCRIPTS_LINT=true
      script: ./packages/scripts/src/bash/ci-test.sh

    - stage: test
      name: 'Test backend and migrations'
      env:
        - CI_INSTALL_BACKEND=true
        - CI_INSTALL_COMMON=true
        - CI_INSTALL_MIGRATIONS=true
        - CI_INSTALL_SCRIPTS=true
        - CI_LINK_BACKEND=true
        - CI_LINK_COMMON=true
        - CI_LINK_MIGRATIONS=true
        - CI_LINK_SCRIPTS=true
        - CI_START_API=true
        - CI_START_DATABASES=true
        - CI_TEST_BACKEND_API=true
        - CI_TEST_BACKEND_DB=true
        - CI_TEST_BACKEND_LINT=true
        - CI_TEST_BACKEND_UNIT=true
        - CI_TEST_MIGRATIONS_LINT=true
        - DISABLE_AUTH=true
      script: ./packages/scripts/src/bash/ci-test.sh

    - stage: build
      name: 'Build backend and migrations'
      env:
        - CI_BUILD_BACKEND=true
        - CI_BUILD_MIGRATIONS=true
        - CI_TAG_LATEST=true
        - CI_PUBLISH_API=true
        - CI_PUBLISH_MIGRATIONS=true
      script:
        ./packages/scripts/src/bash/ci-build.sh &&
        ./packages/scripts/src/bash/ci-publish-docker.sh

    - stage: build
      name: 'Build ui'
      env:
        - CI_INSTALL_UI=true
        - CI_BUILD_UI=true
        - CI_TAG_LATEST=true
        - CI_PUBLISH_UI=true
      script:
        ./packages/scripts/src/bash/ci-build.sh &&
        ./packages/scripts/src/bash/ci-publish-docker.sh

    - stage: build
      name: 'Build style'
      env:
        - CI_INSTALL_STYLE=true
        - CI_BUILD_STYLE=true
        - CI_TAG_LATEST=true
        - CI_PUBLISH_STYLE=true
      script:
        ./packages/scripts/src/bash/ci-build.sh &&
        ./packages/scripts/src/bash/ci-publish-docker.sh

    - stage: build
      name: 'Build docs'
      env:
        - CI_INSTALL_DOCS=true
        - CI_BUILD_DOCS=true
        - CI_TAG_LATEST=true
        - CI_PUBLISH_DOCS=true
      script:
        ./packages/scripts/src/bash/ci-build.sh &&
        ./packages/scripts/src/bash/ci-publish-docker.sh

stages:
  - name: test
  - name: build
    if: tag IS present

branches:
  except:
    - master

services:
  - docker

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

install:
  - echo "$TRAVIS_TAG"
  - ./packages/scripts/src/bash/ci-install.sh

before_script:
  - ./packages/scripts/src/bash/ci-before-script.sh
