language: node_js

matrix:
  include:
    - stage: build
      name: 'Build api, docs, migrations and style'
      env:
        - CI_BUILD_API=true
        - CI_BUILD_DOCS=true
        - CI_BUILD_MIGRATIONS=true
        - CI_BUILD_STYLE=true
        - CI_INSTALL_DOCS=true
        - CI_INSTALL_STYLE=true
      script:
        ./packages/scripts/src/bash/ci-build.sh &&
        ./packages/scripts/src/bash/ci-push-temporary-images.sh

    - stage: build
      name: 'Build ui'
      env:
        - CI_BUILD_UI=true
        - CI_INSTALL_UI=true
      script:
        ./packages/scripts/src/bash/ci-build.sh &&
        ./packages/scripts/src/bash/ci-push-temporary-images.sh

    - stage: test
      name: 'Test e2e part 1'
      env:
        - CI_INSTALL_SCRIPTS=true
        - CI_INSTALL_UI=true
        - CI_SETUP_ENV_DOCKER=true
        - CI_START_E2E=true
        - CI_TEST_E2E_1=true
      script: ./packages/scripts/src/bash/ci-test.sh

    - stage: test
      name: 'Test e2e part 2'
      env:
        - CI_INSTALL_SCRIPTS=true
        - CI_INSTALL_UI=true
        - CI_SETUP_ENV_DOCKER=true
        - CI_START_E2E=true
        - CI_TEST_E2E_2=true
      script: ./packages/scripts/src/bash/ci-test.sh

    - stage: test
      name: 'Test backend and migrations'
      env:
        - CI_INSTALL_BACKEND=true
        - CI_INSTALL_COMMON=true
        - CI_INSTALL_MIGRATIONS=true
        - CI_INSTALL_SCRIPTS=true
        - CI_LINK_BACKEND=true
        - CI_LINK_COMMON=true
        - CI_LINK_MIGRATIONS=true
        - CI_LINK_SCRIPTS=true
        - CI_START_API=true
        - CI_TEST_BACKEND_API=true
        - CI_TEST_BACKEND_DB=true
        - CI_TEST_BACKEND_LINT=true
        - CI_TEST_BACKEND_UNIT=true
        - CI_TEST_MIGRATIONS_LINT=true
      script: ./packages/scripts/src/bash/ci-test.sh

    - stage: test
      name: 'Test common, docs, models, scripts and ui'
      env:
        - CI_INSTALL_UI=true
        - CI_INSTALL_COMMON=true
        - CI_INSTALL_DOCS=true
        - CI_INSTALL_MODELS=true
        - CI_INSTALL_SCRIPTS=true
        - CI_TEST_COMMON_LINT=true
        - CI_TEST_COMMON_UNIT=true
        - CI_TEST_DOCS_LINT=true
        - CI_TEST_DOCS_UNIT=true
        - CI_TEST_MODELS_LINT=true
        - CI_TEST_MODELS_LINT=true
        - CI_TEST_SCRIPTS_LINT=true
        - CI_TEST_UI_LINT=true
        - CI_TEST_UI_UNIT=true
      script: ./packages/scripts/src/bash/ci-test.sh

    - stage: publish and cleanup
      name: 'Publish docker images and delete temporary docker images'
      script:
        ./packages/scripts/src/bash/ci-publish.sh &&
        ./packages/scripts/src/bash/ci-delete-temporary-images.sh

    - stage: cleanup
      name: 'Delete temporary docker images'
      script: ./packages/scripts/src/bash/ci-delete-temporary-images.sh

stages:
  - name: build
  - name: test
  - name: cleanup
    if: tag IS blank
  - name: publish and cleanup
    if: tag IS present

addons:
  hosts:
    - local-api.dina-web.net
    - local-docs.dina-web.net
    - local-keycloak.dina-web.net
    - local-style.dina-web.net
    - local-ui.dina-web.net

branches:
  except:
    - master

services:
  - docker

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

install:
  - echo "$TRAVIS_TAG"
  - ./packages/scripts/src/bash/ci-install.sh

before_script:
  - ./packages/scripts/src/bash/ci-before-script.sh

after_failure:
  - ./packages/scripts/src/bash/ci-delete-temporary-images.sh
