language: node_js

services:
  - docker

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  - yarn install

before_script:
  - export PUSH_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo ""; fi)
  - echo "PUSH_BRANCH=$PUSH_BRANCH, TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST, TRAVIS_BRANCH=$TRAVIS_BRANCH"

script:
  - yarn test

after_success:
  - echo "After success"
  - if [ "$PUSH_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    yarn build:ui;
    echo "Start dina-collections-ui build";
    docker build -f ./packages/ui/Dockerfile -t dina-collections-ui ./packages/ui;
    docker tag dina-collections-ui dina/dina-collections-ui;
    docker push dina/dina-collections-ui;

    echo "Start dina-collections-ui mock build";
    yarn build:ui:mock;
    docker build -f ./packages/ui/Dockerfile -t dina-collections-ui-mock ./packages/ui;
    docker tag dina-collections-ui-mock dina/dina-collections-ui-mock;
    docker push dina/dina-collections-ui-mock;

    echo "Start dina-semantic-ui build";
    yarn build:semantic-ui;
    docker build -f ./packages/dina-semantic-ui/Dockerfile -t dina-semantic-ui-docs ./packages/dina-semantic-ui;
    docker tag dina-semantic-ui-docs dina/dina-semantic-ui-docs;
    docker push dina/dina-semantic-ui-docs;

    yarn uninstall;
    echo "Start dina-collections-api build";
    docker build -f ./packages/api/Dockerfile -t api ./packages;
    docker tag dina-collections-api dina/dina-collections-api;
    docker push dina/dina-collections-api;
    fi
