version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    container_name: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data

    env_file:
      - ./env/.elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    container_name: kibana
    ports:
      - 5601:5601

  postgres:
    image: postgres:10.5
    container_name: postgres
    ports:
    - 5432:5432
    env_file:
      - ./env/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:3.4
    container_name: pgadmin4
    ports:
      - 19090:80
    env_file:
      - ./env/.pgadmin
    volumes:
      - pgadmin_vol:/var/lib/pgadmin

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  postgres_data:
  es_data:
  pgadmin_vol:
