version: '3.3'
services:
  keycloak:
    volumes:
      - ./packages/keycloak/themes/dina:/opt/jboss/keycloak/themes/dina
      - ./packages/keycloak/dina-realm-dev.json:/opt/jboss/keycloak/dev-export.json

  ui:
    ports:
      - 80:80
    depends_on:
      - api
