version: '3.3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    container_name: kibana
    ports:
      - 5601:5601

  pgadmin:
    image: dpage/pgadmin4:3.4
    container_name: pgadmin4
    ports:
      - 19090:80
    env_file:
      - ./env/.pgadmin
    volumes:
      - pgadmin_vol:/var/lib/pgadmin

networks:
  default:
    external:
      name: dinacollections_default
volumes:
  pgadmin_vol:
