version: '3.3'
services:
  import:
    image: "dina/dina-collections-migrations:${TAG}"
    container_name: dina-migrations-import
    env_file:
      - ./env/.backend
    command: yarn --cwd=/etc/packages/migrations setup:production
    volumes:
      - ./data:/etc/data
      - ./userFiles:/etc/userFiles
  rebuildSearch:
    image: "dina/dina-collections-migrations:${TAG}"
    container_name: dina-migrations-rebuild-search
    env_file:
      - ./env/.backend
    command: yarn --cwd=/etc/packages/migrations elasticsearch:production:rebuild-indices
    volumes:
      - ./data:/etc/data
      - ./userFiles:/etc/userFiles

  migrateOne:
    image: "dina/dina-collections-migrations:${TAG}"
    container_name: dina-migrations-migrate-one
    env_file:
      - ./env/.backend
    command: yarn --cwd=/etc/packages/migrations db:production:migrate:one
    volumes:
      - ./data:/etc/data
      - ./userFiles:/etc/userFiles

  migrateLatest:
    image: "dina/dina-collections-migrations:${TAG}"
    container_name: dina-migrations-migrate-latest
    env_file:
      - ./env/.backend
    command: yarn --cwd=/etc/packages/migrations db:production:migrate:latest
    volumes:
      - ./data:/etc/data
      - ./userFiles:/etc/userFiles

  migrateUndoOne:
    image: "dina/dina-collections-migrations:${TAG}"
    container_name: dina-migrations-migrate-undo-one
    env_file:
      - ./env/.backend
    command: yarn --cwd=/etc/packages/migrations db:production:migrate:undo:one
    volumes:
      - ./data:/etc/data
      - ./userFiles:/etc/userFiles

networks:
  default:
    external:
      name: dina-collections_default

volumes:
  postgres_data:
  es_data:
