version: '3.3'
services:
  loadData:
    image: "dina/dina-collections-api:${TAG}"
    container_name: load-data
    environment:
      - IMPORT_DATA=true
      - IMPORT_DATA_NUMBER_OF_SPECIMENS=1000000
      - DEBUG=DINA:LOG_INFO*
    env_file:
      - ./env/.backend
    command: node /etc/api/src/apps/production/data/index.js
    volumes:
      - ./data:/data
      - ./userFiles:/userFiles

networks:
  default:
    external:
      name: dina-collections_default

volumes:
  postgres_data:
  es_data:
