version: '3.3'
services:
  dockerhub-hook:
    image: maccyber/micro-dockerhub-hook
    ports:
      - "8004:3000"
    env_file:
      - ./env/.docker-hook
    volumes:
      - ./docker-hooks:/src/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/var/dina-collections

  ui:
    image: dina/dina-collections-ui
    container_name: dina-collections-ui
    expose:
    - "80"
    env_file:
      - ./env/.ui
    command: /bin/bash -c "envsubst '$$NGINX_TAXONOMY_API_BASE_URL $$NGINX_API_BASE_URL $$NGINX_HOST $$NGINX_PORT $$NGINX_AUTH_BASE_URL' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - api

  style:
    image: dina/dina-semantic-ui-docs
    container_name: dina-semantic-ui-docs
    expose:
    - "80"
    env_file:
      - ./env/.style
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  api:
    image: dina/dina-collections-api
    container_name: dina-api
    expose:
    - "80"
    env_file:
      - ./env/.backend

    command: pm2-runtime start /etc/api/src/apps/production/api/index.js
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - ./data:/data

  worker:
    image: dina/dina-collections-api
    container_name: dina-worker
    env_file:
      - ./env/.backend
    command: pm2-runtime start /etc/api/src/apps/worker/api/index.js
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - ./data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    container_name: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data

    env_file:
      - ./env/.elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    container_name: kibana
    ports:
      - 5601:5601

  postgres:
    image: postgres:10.5
    container_name: postgres
    ports:
    - 5432:5432
    env_file:
      - ./env/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:3.4
    container_name: pgadmin4
    ports:
      - 19090:80
    env_file:
      - ./env/.pgadmin
    volumes:
      - pgadmin_vol:/var/lib/pgadmin

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  postgres_data:
  es_data:
  pgadmin_vol:
