version: '3.3'
services:
  loadData:
    image: dina/dina-collections-api
    container_name: load-data
    environment:
      - IMPORT_DATA=true
      - IMPORT_DATA_NUMBER_OF_SPECIMENS=1000000
    env_file:
      - ./env/.backend
    command: node /etc/api/src/apps/production/data/index.js
    volumes:
      - ./data:/data
      - ./userFiles:/userFiles

networks:
  default:
    external:
      name: proxy-docker_default

volumes:
  postgres_data:
  es_data:

