version: '3.3'
services:
  loadData:
    image: dina/dina-collections-api
    container_name: load-data
    environment:
      - LOAD_INITIAL_DATA=true
      - INITIAL_DATA_NUMBER_OF_SPECIMENS=100
    env_file:
      - ./env/.backend
    command: node /etc/api/src/apps/production/data/index.js
    volumes:
      - ./data:/data

networks:
  default:
    external:
      name: dwproxy_default

volumes:
  postgres_data:
  es_data:

