version: '3.3'
services:
  ui:
    image: 'dina/dina-collections-ui:ci'
    container_name: dina-collections-ui
    network_mode: host
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=3000
    ports:
      - 3000:3000
    command:
      /bin/bash -c "envsubst '$$NGINX_API_BASE_URL $$NGINX_HOST $$NGINX_PORT
      $$NGINX_AUTH_BASE_URL' < /etc/nginx/conf.d/default.template >
      /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
