version: '3.3'
services:
  migrations:
    image: dina/dina-collections-migrations
    container_name: dina-migrations
    env_file:
      - ./env/.backend
    environment:
      BACKEND_IN_NODE_MODULES: 'true'
    command: yarn --cwd=/etc/migrations setup:production
    volumes:
      - ./data:/data
      - ./userFiles:/userFiles


networks:
  default:
    external:
      name: dinacollections_default

volumes:
  postgres_data:
  es_data:

