version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    container_name: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data

    env_file:
      - ./env/.elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    container_name: kibana
    ports:
      - 5601:5601

  postgres:
    image: postgres:10.5
    container_name: postgres
    ports:
    - 5432:5432
    env_file:
      - ./env/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:3.4
    container_name: pgadmin4
    ports:
      - 19090:80
    env_file:
      - ./env/.pgadmin
    volumes:
      - pgadmin_vol:/var/lib/pgadmin

  mysql:
    image: mysql:5.7
    container_name: keycloak-mysql
    env_file: ./env/.local.mysql
    volumes:
      - mysql-keycloak-accounts:/var/lib/mysql
  keycloak:
    image: jboss/keycloak:3.2.1.Final #this is the latest
    container_name: keycloak
    links:
      - mysql:mysql # No need for this??

    # Username & password to use the database
    env_file: ./env/.local.keycloak

    environment:
      # Select database
      - DB_VENDOR=MYSQL
      # proxy address forwarding, needed when running Keycloak behind a proxy
      - PROXY_ADDRESS_FORWARDING=true
      - TZ=Europe/Stockholm
      # URL for proxy server
    ports:
      - 8080:8080
    volumes:
      - ./packages/keycloak/configuration/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
      - ./packages/keycloak/themes/dina:/opt/jboss/keycloak/themes/dina
    depends_on:
      - mysql

volumes:
  postgres_data:
  es_data:
  pgadmin_vol:
  mysql-keycloak-accounts:






