version: '3.3'
services:
  api:
    image: "dina/dina-collections-api:${TAG}"
    container_name: dina-api
    expose:
    - "80"
    env_file:
      - ./env/.backend
    command: pm2-runtime start /etc/api/src/apps/production/api/index.js
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - ./data:/data
      - ./userFiles:/userFiles

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    container_name: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
    env_file:
      - ./env/.elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  keycloak:
    image: jboss/keycloak:4.5.0.Final #this is the latest
    container_name: keycloak
    # Username & password to use the database
    env_file: ./env/.keycloak

    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
    ports:
      - 8080:8080
    volumes:
      - ./packages/keycloak/themes/dina:/opt/jboss/keycloak/themes/dina
      - ./packages/keycloak/dev-export.json:/opt/jboss/keycloak/dev-export.json
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: keycloak-mysql
    env_file: ./env/.mysql
    volumes:
      - mysql-keycloak-accounts:/var/lib/mysql


  postgres:
    image: postgres:10.5
    container_name: postgres
    env_file:
      - ./env/.postgres
    restart: always    
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  proxy:
    image: jwilder/nginx-proxy:latest
    container_name: proxy
    environment:
      - NGINX_MAX_BODY_SZ=100m
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./packages/proxy/site.template:/etc/nginx/conf.d/site.template
      #- /etc/localtime:/etc/localtime
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/dina.conf && forego start -r"

  style:
    image: "dina/dina-semantic-ui-docs:latest"
    container_name: dina-semantic-ui-docs
    expose:
    - "80"
    env_file:
      - ./env/.style
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  ui:
    image: "dina/dina-collections-ui:${TAG}"
    container_name: dina-collections-ui
    expose:
    - "80"
    env_file:
      - ./env/.ui
    command: /bin/bash -c "envsubst '$$NGINX_TAXONOMY_API_BASE_URL $$NGINX_API_BASE_URL $$NGINX_HOST $$NGINX_PORT $$NGINX_AUTH_BASE_URL' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - api
      - keycloak

  worker:
    image: "dina/dina-collections-api:${TAG}"
    container_name: dina-worker
    env_file:
      - ./env/.backend
    command: pm2-runtime start /etc/api/src/apps/production/worker/index.js
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - ./data:/data
      - ./userFiles:/userFiles

volumes:
  postgres_data:
  es_data:
  mysql-keycloak-accounts:
